spring:
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    openfeign:
      client:
        config:
          account-service:
            url: http://localhost:8082
          bargain-service:
            url: http://localhost:8084
  autoconfigure:
    exclude:
      - com.alibaba.cloud.nacos.NacosDiscoveryAutoConfiguration
      - com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
